import type { StateSlug } from "../../site.config";
import localJson from "../data/local.json";

/**
 * Local-data layer for every county, town and team-city page.
 *
 * Generated by research/local/build_local.py from public sources only:
 * - Census ACS 2023 5-year estimates (children, broadband, children's
 *   insurance mix, working parents, income, child poverty)
 * - Census 2024 Gazetteer (coordinates, land area)
 * - Census 2020 ZCTA relationship files (ZIP codes)
 * - NCES Common Core of Data 2022 via the Urban Institute (school districts)
 * - Wikidata (county seats)
 *
 * Distances are straight-line miles between Census interior points — they
 * are labeled "about N miles" everywhere and never presented as drive time.
 */

export interface LocalStats {
  pop: number;
  under5: number;
  under18: number;
  under6: number;
  under6AllParentsWorkPct: number | null;
  households: number;
  broadbandPct: number | null;
  kidsUninsuredPct: number | null;
  kidsPublicOnlyPct: number | null;
  medianIncome: number | null;
  childPovertyPct: number | null;
}

export interface District {
  name: string;
  city: string;
  enrollment: number;
  schools: number | null;
}

export interface Hub {
  slug: string;
  name: string;
  miles: number;
}

export interface NearbyPage {
  /** "county/town" for a town page, or a city slug for a team-city page. */
  path: string;
  name: string;
  miles: number;
  kind: "town" | "city";
}

export interface CountyLocal {
  seat: string | null;
  landSqMi: number;
  stats: LocalStats | null;
  zips: string[];
  districts: District[];
  districtCount: number;
  hub: Hub;
  neighborMiles: { slug: string; miles: number }[];
  townMiles: Record<string, number>;
}

export interface PlaceLocal {
  kind: "incorporated" | "cdp";
  landSqMi: number;
  stats: LocalStats | null;
  zips: string[];
  districts: District[];
  isSeat: boolean;
  hub: Hub;
  nearby: NearbyPage[];
  otherCounties: string[];
}

export interface CityLocal {
  county: string;
  landSqMi: number;
  stats: LocalStats | null;
  zips: string[];
  districts: District[];
  within30: NearbyPage[];
  nearby: NearbyPage[];
  countiesServed: string[];
}

interface StateLocal {
  counties: Record<string, CountyLocal>;
  places: Record<string, PlaceLocal>;
  cities: Record<string, CityLocal>;
}

const local = localJson as unknown as Record<StateSlug, StateLocal>;

export function countyLocal(state: StateSlug, slug: string): CountyLocal | undefined {
  return local[state].counties[slug];
}

export function placeLocal(
  state: StateSlug,
  county: string,
  town: string
): PlaceLocal | undefined {
  return local[state].places[`${county}/${town}`];
}

export function cityLocal(state: StateSlug, slug: string): CityLocal | undefined {
  return local[state].cities[slug];
}

/** Statewide totals rolled up from the county records. */
export function stateTotals(state: StateSlug) {
  let under18 = 0;
  let under5 = 0;
  let pop = 0;
  for (const c of Object.values(local[state].counties)) {
    under18 += c.stats?.under18 ?? 0;
    under5 += c.stats?.under5 ?? 0;
    pop += c.stats?.pop ?? 0;
  }
  return { under18, under5, pop };
}

/** Href for a NearbyPage entry. */
export function nearbyHref(state: StateSlug, n: NearbyPage): string {
  return `/${state}/${n.path}`;
}

/** CDC ADDM (2025 report, 2022 surveillance year): about 1 in 31 children. */
export const CDC_RATE = 31;

export function autismEstimate(under18: number): number {
  return Math.round(under18 / CDC_RATE);
}

export const fmt = (n: number) => n.toLocaleString("en-US");

/** Rounds to a friendly figure: 1,234 -> "about 1,200". */
export function about(n: number): string {
  if (n < 20) return `about ${n}`;
  const mag = n < 1000 ? 10 : n < 10000 ? 100 : n < 100000 ? 1000 : 10000;
  return `about ${fmt(Math.round(n / mag) * mag)}`;
}

export const pctStr = (p: number) =>
  `${p >= 10 ? Math.round(p) : Math.round(p * 10) / 10}%`;

export function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h;
}

/** Deterministic pick so a page's wording is stable across builds. */
export function pick<T>(seed: number, salt: number, options: T[]): T {
  return options[(Math.imul(seed ^ (salt * 40503), 2654435761) >>> 0) % options.length];
}

export const SOURCES_NOTE =
  "Sources: Census ACS 2023 5-year estimates; Census ZIP-code relationship files; NCES school-district data. The autism figure applies the CDC’s 1-in-31 estimate — a planning number, not a count. Miles are straight-line.";

/** Statewide rates, weighted from county figures. */
export function stateRates(state: StateSlug) {
  let u6 = 0, u6w = 0, hh = 0, hhb = 0;
  for (const c of Object.values(local[state].counties)) {
    const s = c.stats;
    if (!s) continue;
    if (s.under6AllParentsWorkPct !== null) {
      u6 += s.under6;
      u6w += (s.under6 * s.under6AllParentsWorkPct) / 100;
    }
    if (s.broadbandPct !== null) {
      hh += s.households;
      hhb += (s.households * s.broadbandPct) / 100;
    }
  }
  return {
    under6AllParentsWorkPct: u6 ? (100 * u6w) / u6 : null,
    broadbandPct: hh ? (100 * hhb) / hh : null,
    under6: u6,
  };
}
