import type { StateSlug } from "../../site.config";
import townsJson from "./towns.json";

/**
 * Town dataset for the /{state}/{county}/{town} pages — every Census
 * incorporated place, nested under its county.
 *
 * Generated by scripts/build-towns.mjs from the Census 2024 place
 * estimates (research/places_ks_co.json) + the SUMLEV 157 county-place
 * parts (research/sub-est2024.csv). A place that spans counties lives
 * under the county holding its largest population part.
 *
 * - `towns` (pop >= 100) get real pages, sorted by population desc.
 * - `tiny` (pop < 100) get NO page — the county page names them in a
 *   plain-text "every community" line instead, so coverage is honest
 *   without minting junk pages.
 * - `cityRedirects` are the 10 places that already have first-class city
 *   pages at /{state}/{city}; next.config.ts 301s their town URLs there.
 *
 * Slugs are unique within each county (verified at generation time);
 * same-name towns in different counties coexist because pages nest under
 * the county.
 */

export interface TownEntry {
  /** Display name, e.g. "Salina" (Census type suffix stripped). */
  name: string;
  slug: string;
  /** Census 2024 population estimate. */
  pop: number;
  /** Slug of the county the town belongs to. */
  county: string;
}

export interface CityRedirect {
  county: string;
  slug: string;
  /** Existing city-page slug at /{state}/{city}. */
  city: string;
}

interface StateTowns {
  towns: TownEntry[];
  tiny: TownEntry[];
  cityRedirects: CityRedirect[];
}

export const townsByState = townsJson as Record<StateSlug, StateTowns>;

const lookup: Record<StateSlug, Map<string, TownEntry>> = {
  kansas: new Map(
    townsByState.kansas.towns.map((t) => [`${t.county}/${t.slug}`, t])
  ),
  colorado: new Map(
    townsByState.colorado.towns.map((t) => [`${t.county}/${t.slug}`, t])
  ),
};

export function getTown(
  state: StateSlug,
  countySlug: string,
  townSlug: string
): TownEntry | undefined {
  return lookup[state].get(`${countySlug}/${townSlug}`);
}

/** All page-worthy towns in a county, already population-sorted. */
export function townsInCounty(
  state: StateSlug,
  countySlug: string
): TownEntry[] {
  return townsByState[state].towns.filter((t) => t.county === countySlug);
}

/** Sub-100-population places in a county (plain-text mention only). */
export function tinyPlacesInCounty(
  state: StateSlug,
  countySlug: string
): TownEntry[] {
  return townsByState[state].tiny.filter((t) => t.county === countySlug);
}

/** City-page places located in a county (chips link to /{state}/{city}). */
export function cityPagesInCounty(
  state: StateSlug,
  countySlug: string
): CityRedirect[] {
  return townsByState[state].cityRedirects.filter(
    (r) => r.county === countySlug
  );
}
